### PR TITLE
build error on humble: missing rosbag2_storage package

### PR DESCRIPTION
**Pull request by tfoldi**
When building on Humble first of all we have this error message:

```
tfoldi@raspberrypi:~/unitree/unitree.ws$ colcon build
Starting >>> unitree_api
Starting >>> unitree_go
Finished <<< unitree_api [8.03s]
Finished <<< unitree_go [13.3s]
Starting >>> go2_demo
--- stderr: go2_demo
/home/tfoldi/unitree/unitree.ws/src/unitree_ros2/Go2_ROS2_example/src/src/record_bag.cpp: In constructor ‘motion_state_suber::motion_state_suber()’:
/home/tfoldi/unitree/unitree.ws/src/unitree_ros2/Go2_ROS2_example/src/src/record_bag.cpp:29:28: error: ‘StorageOptions’ in namespace ‘rosbag2_cpp’ does not name a type
   29 |         const rosbag2_cpp::StorageOptions storage_options({"timed_synthetic_bag", "sqlite3"});
      |                            ^~~~~~~~~~~~~~
/home/tfoldi/unitree/unitree.ws/src/unitree_ros2/Go2_ROS2_example/src/src/record_bag.cpp:29:93: error: expected primary-expression before ‘)’ token
   29 |         const rosbag2_cpp::StorageOptions storage_options({"timed_synthetic_bag", "sqlite3"});
      |                                                                                             ^
/home/tfoldi/unitree/unitree.ws/src/unitree_ros2/Go2_ROS2_example/src/src/record_bag.cpp:35:23: error: ‘storage_options’ was not declared in this scope
   35 |         writer_->open(storage_options, converter_options);
      |                       ^~~~~~~~~~~~~~~
gmake[2]: *** [CMakeFiles/record_bag.dir/build.make:76: CMakeFiles/record_bag.dir/src/record_bag.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:251: CMakeFiles/record_bag.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< go2_demo [21.1s, exited with code 2]

Summary: 2 packages finished [39.1s]
  1 package failed: go2_demo
  1 package had stderr output: go2_demo
```

To fix this we should switch from the deprecated `rosbag2_cpp::StorageOptions` to `rosbag2_storage::StorageOptions`, as implemented in the PR.

### CODE REVIEW

**Comment by wuyangning** [comment]
The usage of `rosbag2` is different in `ros2-foxy` and `ros2-humble`. `record bag.cpp` example provided in repositorie is based on `ros2-foxy`. For details, please refer to:
- [foxy rosbag2](https://docs.ros.org/en/foxy/Tutorials/Advanced/Recording-A-Bag-From-Your-Own-Node-CPP.html)
- [humble rosbag2](https://docs.ros.org/en/humble/Tutorials/Advanced/Recording-A-Bag-From-Your-Own-Node-CPP.html)

**Comment by tfoldi** [comment]
fair point. in that case I believe using `ROSBAG2_STORAGE__STORAGE_OPTIONS_HPP_` or  `ROSBAG2_CPP__STORAGE_OPTIONS_HPP_`  should be the right approach to see where to include the header file. Would that work?

**Comment by UNSaWEN** [comment]
> fair point. in that case I believe using `ROSBAG2_STORAGE__STORAGE_OPTIONS_HPP_` or  `ROSBAG2_CPP__STORAGE_OPTIONS_HPP_`  should be the right approach to see where to include the header file. Would that work?

Got same qusetion，sovled.

**Comment by FranekStark** [comment]
@wuyangning does this pull request affect the functionality in foxy? Otherwise, I would ask to merge this asap.  ROS2 foxy reached its EOL already. Hence, most of the people will use Humble instead.

**Comment by tfoldi** [comment]
I'll update the pr with both foxy any humble support

**Comment by tfoldi** [comment]
I built and tested on a few platforms, plus added basic CI/CD actions to check how it compiles on other ROS2 distros:

image

Hope it can be merged soon.

**Comment by wuyangning** [comment]
> I built and tested on a few platforms, plus added basic CI/CD actions to check how it compiles on other ROS2 distros:
> 
> image
> Hope it can be merged soon.

Thank you for your support. We will create a new branch for other versions of ROS2 after passing the test. Since the recommended environment for Unitree sdk2 is Ubuntu 20.04,  the main branch will retain the Foxy for better hardware support.

**Comment by it5meyash** [comment]
I noticed a potential discrepancy in the file record_bag.cpp within the unitree_ros2/Go2_ROS2_example/src/src/ directory.

In line 29, there's a declaration using rosbag2_cpp::StorageOptions as follows:

const rosbag2_cpp::StorageOptions storage_options({"timed_synthetic_bag", "sqlite3"});

However, based on my understanding, it seems like it should be using rosbag2_storage instead of rosbag2_cpp. So, the corrected line would be:

const rosbag2_storage::StorageOptions storage_options({"timed_synthetic_bag", "sqlite3"});

please check while doing colcon build it's showing error!

**Pull request closed without merging**
